apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcloud-cosi-driver.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "hcloud-cosi-driver.labels" . | nindent 4 }}
automountServiceAccountToken: true
