image:
  repository: ghcr.io/espresso-lab/hcloud-cosi-driver
  tag: main
  pullPolicy: IfNotPresent

sidecar:
  image:
    repository: registry.k8s.io/sig-storage/objectstorage-sidecar
    tag: v0.2.2
    pullPolicy: IfNotPresent
